# Generated by Django 3.1.7 on 2021-05-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210524_1449'),
        ('specifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySpecifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('spec_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specifications.specificationpreset')),
            ],
        ),
    ]
