# Generated by Django 3.1.7 on 2021-05-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210524_1449'),
        ('specifications', '0003_auto_20210528_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specification',
            old_name='spec_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='specificationpreset',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.DeleteModel(
            name='CategorySpecifications',
        ),
    ]
