# Generated by Django 3.1.7 on 2021-05-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210524_1449'),
        ('specifications', '0004_auto_20210528_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationpreset',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='main.category'),
        ),
    ]
