# Generated by Django 3.1.7 on 2021-06-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0005_auto_20210528_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationpreset',
            name='is_filter',
            field=models.BooleanField(default=False),
        ),
    ]
