# Generated by Django 3.1.7 on 2021-06-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='posted',
            field=models.BooleanField(default=True),
        ),
    ]
