# Generated by Django 3.1.7 on 2021-05-22 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=516, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date')),
                ('price', models.DecimalField(decimal_places=1, max_digits=10000, verbose_name='Price')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.category')),
            ],
        ),
    ]
