# Generated by Django 3.1.7 on 2021-05-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=255)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_type', models.CharField(choices=[('pk', 'pickup'), ('dl', 'delivery')], max_length=1000)),
                ('comment', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
