# Generated by Django 3.1.7 on 2021-05-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('', 'other'), ('pk', 'pickup'), ('dl', 'delivery')], max_length=1000),
        ),
    ]
